### ISSUE TITLE
Refactor Hunt.rb

### ISSUE THREAD

**Issue by scott-ad-riley** [scott-ad-riley/rpg-bear-terminal-game#2]
To seperate game logic and display output, we need to split hunt.rb's puts outputs into a seperate viewer class that is called when game.rb is called.

Once this is done we can build out the test spec for the hunt class.

**Comment by singhprd** [comment]
Take out PUTS from functions/methods because it makes it easier to TDD

**Comment by singhprd** [comment]
Hunt doesn't add food to Bear properly.

**Comment by scott-ad-riley** [comment]
Fixed in f99c07d. Though compromised by removing the choice to fight when you hunt.
